-- 学生选课系统建表脚本（PostgreSQL）
-- 说明：原《系统设计文档》以 MySQL 编写，此处按 PostgreSQL 语法等价改写
-- （自增列 -> IDENTITY，生成列 -> GENERATED ... STORED）

CREATE TABLE IF NOT EXISTS college (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS student (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_no VARCHAR(20)  NOT NULL UNIQUE,
    password   VARCHAR(100) NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    gender     VARCHAR(4),
    major      VARCHAR(50),
    grade      VARCHAR(10),
    phone      VARCHAR(20),
    email      VARCHAR(50),
    college_id BIGINT
);

CREATE TABLE IF NOT EXISTS course (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_no  VARCHAR(20)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    credit     NUMERIC(3,1) NOT NULL,
    category   VARCHAR(20)  NOT NULL,
    college_id BIGINT
);

CREATE TABLE IF NOT EXISTS teaching_class (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id      BIGINT       NOT NULL,
    class_name     VARCHAR(100) NOT NULL,
    teacher        VARCHAR(50),
    class_time     VARCHAR(100),
    classroom      VARCHAR(100),
    day_of_week    SMALLINT     NOT NULL,
    start_section  SMALLINT     NOT NULL,
    end_section    SMALLINT     NOT NULL,
    start_week     SMALLINT     NOT NULL,
    end_week       SMALLINT     NOT NULL,
    capacity       INTEGER      NOT NULL DEFAULT 0,
    selected_count INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_class_course ON teaching_class(course_id);
CREATE INDEX IF NOT EXISTS idx_class_teacher ON teaching_class(teacher);

CREATE TABLE IF NOT EXISTS selection (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        BIGINT    NOT NULL,
    teaching_class_id BIGINT    NOT NULL,
    select_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_selection UNIQUE (student_id, teaching_class_id)
);
CREATE INDEX IF NOT EXISTS idx_selection_class ON selection(teaching_class_id);

CREATE TABLE IF NOT EXISTS wish (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        BIGINT    NOT NULL,
    teaching_class_id BIGINT    NOT NULL,
    create_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wish UNIQUE (student_id, teaching_class_id)
);

CREATE TABLE IF NOT EXISTS waitlist (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        BIGINT    NOT NULL,
    teaching_class_id BIGINT    NOT NULL,
    position          INTEGER   NOT NULL,
    status            SMALLINT  NOT NULL DEFAULT 1,
    create_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_time       TIMESTAMP,
    waiting_flag      SMALLINT GENERATED ALWAYS AS (CASE WHEN status = 1 THEN 1 ELSE NULL END) STORED,
    CONSTRAINT uk_waiting UNIQUE (student_id, teaching_class_id, waiting_flag)
);
CREATE INDEX IF NOT EXISTS idx_waitlist_class ON waitlist(teaching_class_id, status, position);
